username "paul.k.adams@me.com"

app_version "2018.2"
submit_for_review false
automatic_release true
price_tier 5
force true

submission_information({
  add_id_info_uses_idfa: false,
  add_id_info_serves_ads: false,
  add_id_info_tracks_action: false,
  add_id_info_tracks_install: false,
  add_id_info_limits_tracking: false,
  export_compliance_uses_encryption: false,
  export_compliance_encryption_updated: false})

app_review_information(
	first_name: "Paul",
	last_name: "Adams",
	phone_number: "(615) 556-6507",
	email_address: "paul@pkadams67.io",
	demo_user: "demo",
	demo_password: "password",
	notes: "Thanks for reviewing my app!")
