update_fastlane

default_platform :ios

platform :ios do
before_all do
end

lane :Lent2018 do

	match(type: "appstore",
		app_identifier: "io.pkadams67.lent2018",
		git_url: "https://github.com/pkadams67/lent2018certificaterepo")	

	pem(development: false, 
		app_identifier: "io.pkadams67.lent2018",
		pem_name: "io.pkadams67.lent2018_push_production",
		generate_p12: true, 
		p12_password: "JDKExmK", 
		force: false,
		save_private_key: true)

  	gym(scheme: "Lent 2018")

  	deliver(skip_binary_upload: false,
    	app_identifier: "io.pkadams67.lent2018",
    	metadata_path: "fastlane/metadata",
    	app_rating_config_path: "fastlane/app_rating/ratings_config.json",
    	screenshots_path: "fastlane/screenshots",
    	skip_screenshots: true)

end

################################################################################

after_all do |lane|
end

################################################################################

error do |lane, exception|
end

################################################################################

end
